name: Postar vídeos Instagram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
    - cron: '0 18 * * *'

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib requests

      - name: Instalar ngrok
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Configurar ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Criar credenciais Drive
        run: echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > service_account.json

      - name: Rodar bot
        env:
          PASTA_PARA_POSTAR: ${{ secrets.PASTA_PARA_POSTAR }}
          PASTA_POSTADOS: ${{ secrets.PASTA_POSTADOS }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
        run: python main.py
