name: Postar vídeos automaticamente

permissions:
  contents: write

  
on:
#  schedule:
#    - cron: '0 12 * * *'   # 09h Brasil
#    - cron: '0 18 * * *'   # 15h Brasil
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Instalar ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok

      - name: Configurar ngrok
        run: ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Testar tamanho do token
        run: echo "O token tem ${#TOKEN} caracteres"
        env:
          TOKEN: ${{ secrets.NGROK_AUTHTOKEN }}

      - name: Criar credenciais
        run: |
          echo '${{ secrets.GDRIVE_SERVICE_ACCOUNT }}' > service_account.json

      - name: Rodar script
        env:
          PASTA_PARA_POSTAR: ${{ secrets.PASTA_PARA_POSTAR }}
          PASTA_POSTADOS: ${{ secrets.PASTA_POSTADOS }}
          YOUTUBE_CLIENT_SECRET_JSON: ${{ secrets.YOUTUBE_CLIENT_SECRET_JSON }}
          YOUTUBE_TOKEN_PICKLE: ${{ secrets.YOUTUBE_TOKEN_PICKLE }}
          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }} # <--- ADICIONE ESTA LINHA

        run: python main.py
